### ISSUE TITLE
Create Index With Prefix is not working?

### ISSUE THREAD

**Issue by arv** [rocicorp/replicache#963] opened 2022-04-18 19:12 UTC
According to https://discord.com/channels/@me/900154212007174234/965689701463904307 createIndex with prefix is not working

**Comment by aboodman** [comment] 2022-04-21 20:32
We were not able to reproduce this. waiting for more information from user.

**Comment by aboodman** [comment] 2022-04-26 22:51
User not able to reproduce either. Closing for now.

**Closed as completed by aboodman** 2022-04-26 22:51 UTC
