### ISSUE TITLE
Benchmarks are too noisy

### ISSUE THREAD

**Issue by aboodman** [rocicorp/replicache#124] opened 2020-09-30 19:34 UTC
We sometimes see large moves in the benchmarks because we're running them in github actions which aren't well isolated. We should either move to self-hosted runners or if we could somehow run it a bunch of times on different VMs and take the mean that would work too:

https://docs.github.com/en/free-pro-team@latest/actions/hosting-your-own-runners/about-self-hosted-runners

Actually have a preference for running in ourselves (in ec2 on a dedicated or isolated instance) so that we can control the performance of the machine we're running on.

**Comment by arv** [comment] 2021-07-14 22:22
Duplicate of #216

**Closed by arv** 2021-07-14 22:22 UTC
