### ISSUE TITLE
Database is closing error in heartbeat

### ISSUE THREAD

**Issue by arv** [rocicorp/replicache#843] opened 2022-02-14 16:15 UTC
It is common to close and reopen a db quickly (in react hot module reloading for example) but that leads to issues with the db being in the process of being closed.

Before SDD we had a way to detect this by awaiting the closing promise when we open the db again. I think the `_perdag` db is not doing this as we expect any more leading to this error.

See https://discord.com/channels/830183651022471199/942807273300955187

**Comment by grgbkr** [comment] 2022-02-15 00:52
I'm having difficulty reproducing.

I created [a local version of Replidraw that has basically the same useEffect](https://github.com/rocicorp/replidraw/pull/71/files) setup for creating/closing Replicache as in this [gist ](https://gist.github.com/tmcw/5dd97556d24fa8889c539905d36eb117#file-persisted_map-tsx-L27-L56) from the report over Discord.  This did not manifest the problem.

**Comment by aboodman** [comment] 2022-02-16 08:08
I couldn't reproduce this either by applying Greg's patch to Replidraw. I did verify that the close call is running.

**Closed as completed** 2022-02-24 21:50 UTC
Labels: Next Release
